# Generated by Django 4.1.4 on 2022-12-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=150)),
                ("marca", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
            ],
        ),
    ]
